import React from "react";

const LoadingPage = () => {
  return (
    <div>
      <div className="loadingio-spinner-ball-qa33yf4k4vd">
        <div className="ldio-h3vu9ofvf6f">
          <div />
        </div>
      </div>
      <style
        type="text/css"
        dangerouslySetInnerHTML={{
          __html:
            "\n@keyframes ldio-h3vu9ofvf6f {\n  0%, 100% {\n    animation-timing-function: cubic-bezier(0.45,0,0.9,0.55)\n  }\n  0% {\n    transform: translate(0,0)\n  }\n  50% {\n    transform: translate(0,108px);\n    animation-timing-function: cubic-bezier(0,0.45,0.55,0.9);\n  }\n  100% {\n    transform: translate(0,0);\n  }\n}\n\n.ldio-h3vu9ofvf6f div {\n  position: absolute;\n  width: 52px;\n  height: 52px;\n  border-radius: 50%;\n  background: #fb4226;\n  left: 74px;\n  top: 20px;\n  animation: ldio-h3vu9ofvf6f 1s linear infinite;\n}\n.loadingio-spinner-ball-qa33yf4k4vd {\n  width: 200px;\n  height: 200px;\n  display: inline-block;\n  overflow: hidden;\n  background: #ffffff;\n}\n.ldio-h3vu9ofvf6f {\n  width: 100%;\n  height: 100%;\n  position: relative;\n  transform: translateZ(0) scale(1);\n  backface-visibility: hidden;\n  transform-origin: 0 0; /* see note above */\n}\n.ldio-h3vu9ofvf6f div { box-sizing: content-box; }\n/* generated by https://loading.io/ */\n",
        }}
      />
    </div>
  );
};

export default LoadingPage;
