export const GET_THEATER_REQUEST = "GET_THEATER_REQUEST";
export const GET_THEATER_SUCCESS = "GET_THEATER_SUCCESS";
export const GET_THEATER_FAIL = "GET_THEATER_FAIL";

export const BOOKING_REQUEST = "BOOKING_REQUEST";
export const BOOKING_SUCCESS = "BOOKING_SUCCESS";
export const BOOKING_FAIL = "BOOKING_FAIL";